title: samba-site
description: >
  A Discord.js-powered Discord client framework
baseurl: "/command"
url: "https://discord-samba.github.io"

collections:
  guides:
    permalink: /guides/:title/
    output: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

sass:
  style: compressed

include:
  - "**/*.html" # Needed to include files that start with underscore

exclude:
  - images/edit
  - Gemfile
  - Gemfile.lock
  - README.md
  - typedoc
