name: Build Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: |
          npm install

          # Clone typedoc theme, build, and link because for whatever reason
          # installing the deps and building from within node_modules fails
          cd ../
          git clone https://github.com/discord-samba/typedoc-themes.git
          cd typedoc-themes
          npm install
          npm run build
          npm link

          # CD back to main repo and link theme to dependencies
          cd ../$(echo '${{ github.repository }}' | grep -oP '/\K.+')
          npm link @discord-samba/typedoc-themes

      - name: Build docs
        run: node scripts/typedoc-runner

      - name: Clone gh-pages branch
        run: git clone https://${{ github.actor }}:${{ secrets.DOCS_TOKEN }}@github.com/${{ github.repository }}.git -b gh-pages ../gh-pages

      - name: Prepare docs build
        run: |
          npx gulp gh-docs-prepare
          cp README.md ../gh-pages/_includes/README.md

      - name: Check if commit is needed
        id: git_status
        run: |
          cd ../gh-pages
          echo "##[set-output name=status;]$(git status | grep 'nothing to commit')"

      - name: Make commit and push
        if: contains(steps.git_status.outputs.status, 'nothing to commit') != true
        run: |
          cd ../gh-pages
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor}}@users.noreply.github.com"
          git add --all
          git commit -m "Build docs from master: ${{ github.sha }}"
          git push origin gh-pages
