name: Test Docs

on: pull_request

jobs:
  build:
    name: Test docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm install

          # Clone typedoc theme, build, and link because for whatever reason
          # installing the deps and building from within node_modules fails
          cd ../
          git clone https://github.com/discord-samba/typedoc-themes.git
          cd typedoc-themes
          npm install
          npm run build
          npm link

          # CD back to main repo and link theme to dependencies
          cd ../$(echo '${{ github.repository }}' | grep -oP '/\K.+')
          npm link @discord-samba/typedoc-themes

      - name: Test building docs
        id: build_status
        run: echo "##[set-output name=status;]$(node scripts/typedoc-runner | grep 'Error')"

      - name: Fail if docs build produced errors
        if: contains(steps.build_status.outputs.status, 'Error') != true
        run: exit 1
